// Code generated by mockery v2.8.0. DO NOT EDIT.

package mocks

import (
	cid "github.com/hyperledger/fabric-chaincode-go/pkg/cid"
	mock "github.com/stretchr/testify/mock"

	shim "github.com/hyperledger/fabric-chaincode-go/shim"
)

// VoterNetTransactionContextInterface is an autogenerated mock type for the VoterNetTransactionContextInterface type
type VoterNetTransactionContextInterface struct {
	mock.Mock
}

// GetClientIdentity provides a mock function with given fields:
func (_m *VoterNetTransactionContextInterface) GetClientIdentity() cid.ClientIdentity {
	ret := _m.Called()

	var r0 cid.ClientIdentity
	if rf, ok := ret.Get(0).(func() cid.ClientIdentity); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(cid.ClientIdentity)
		}
	}

	return r0
}

// GetStub provides a mock function with given fields:
func (_m *VoterNetTransactionContextInterface) GetStub() shim.ChaincodeStubInterface {
	ret := _m.Called()

	var r0 shim.ChaincodeStubInterface
	if rf, ok := ret.Get(0).(func() shim.ChaincodeStubInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(shim.ChaincodeStubInterface)
		}
	}

	return r0
}

// GetVoteCountForCand provides a mock function with given fields:
func (_m *VoterNetTransactionContextInterface) GetVoteCountForCand() map[string]int64 {
	ret := _m.Called()

	var r0 map[string]int64
	if rf, ok := ret.Get(0).(func() map[string]int64); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int64)
		}
	}

	return r0
}

// IncrVoteCountForCand provides a mock function with given fields: _a0
func (_m *VoterNetTransactionContextInterface) IncrVoteCountForCand(_a0 string) {
	_m.Called(_a0)
}
